const adminServices = require('../services/admin/adminservices');
var cors = require('cors')
var corsOptions = require('./cors');

exports.routes = function(app) {
    app.post('/addcategory', cors(corsOptions),adminServices.addCategory);
    app.post('/getcategories', cors(corsOptions),adminServices.getCategories);
    app.post('/additem', cors(corsOptions),adminServices.addItem);
    app.post('/getItems', cors(corsOptions),adminServices.getItems);
    //app.post('/totaldata', adminServices.totalData);
    app.post('/getmenucategories', cors(corsOptions),adminServices.getMenuSections);
    app.post('/getmenusections', cors(corsOptions),adminServices.getMenuSection);
    app.post('/getallitems', cors(corsOptions),adminServices.getAllItems);
    app.post('/updatecategory', cors(corsOptions),adminServices.updateCategory);
    app.post('/updateitem', cors(corsOptions),adminServices.updateItem);
    app.post('/deleteitem', cors(corsOptions),adminServices.deleteItem);
    app.post('/updatemenustatus', cors(corsOptions),adminServices.updateMenuStatus);
    app.post('/deletecategory', cors(corsOptions),adminServices.deleteCategory);
    app.post('/addcourse', cors(corsOptions),adminServices.addCourse);
    app.post('/getcourses', cors(corsOptions),adminServices.getCourses);
    app.post('/updatecourse', cors(corsOptions),adminServices.updateCourse);
    app.post('/updatecoursestatus', cors(corsOptions),adminServices.updateCourseStatus);
    app.post('/getmemberrequests', cors(corsOptions),adminServices.getMemberRequests);
    app.post('/getcourseorders', cors(corsOptions),adminServices.getCourseOrders);
    app.post('/getprovinces', cors(corsOptions),adminServices.getProvinces);
    app.get('/generatePDF', cors(corsOptions),adminServices.generatePDF);
    app.post('/generatememberinvoice', cors(corsOptions),adminServices.generateMemberInvoice);
    app.post('/doPayment', cors(corsOptions),adminServices.doPayment);
    app.post('/doesExist', cors(corsOptions),adminServices.doesExist);
    app.post('/doesCartExist', cors(corsOptions),adminServices.doesCartExist);
    app.post('/fetchOrders', cors(corsOptions),adminServices.fetchOrders);
    app.post('/cartLogIn', cors(corsOptions),adminServices.cartLogIn);
    app.post('/changeOrderStatus', cors(corsOptions),adminServices.changeOrderStatus);
    app.post('/updatevendorstatus', cors(corsOptions),adminServices.updateVendorStatus);
    app.post('/generatebstoken', cors(corsOptions),adminServices.generateBSToken);
    app.post('/getsettings', cors(corsOptions),adminServices.getSettings);
    app.put('/updatesettings', cors(corsOptions),adminServices.updateSettings);
    app.put('/updatestatetaxes', cors(corsOptions),adminServices.updateStateTaxes);
    //app.post('/generatedocusign', cors(corsOptions),adminServices.generateDocusign);
    app.post('/generatedocusign', adminServices.generateDocusign);
    app.post('/generatedocusignauth', cors(corsOptions),adminServices.generateDocusignAuth);
    app.post('/getAllCountries', cors(corsOptions),adminServices.getAllCountries);
    app.post('/getstates', cors(corsOptions),adminServices.getStates);
    app.post('/getcities', cors(corsOptions),adminServices.getCities);
    app.post('/generateBsTokenForWeb', cors(corsOptions),adminServices.generateBsTokenForWeb);
    app.post('/get-course-surveys',cors(corsOptions), adminServices.getCourseSurveys);
    app.post('/registercourse', cors(corsOptions),adminServices.registerCourse);
    app.post('/dorecurringpayment', cors(corsOptions),adminServices.doRecurringPayment);
    app.post('/addnewidea', cors(corsOptions),adminServices.addIdea);
    app.post('/getideas', cors(corsOptions),adminServices.getIdeas);
    app.put('/updateidea', cors(corsOptions),adminServices.updateIdea);
};